{
 "title": "BMI Dashboard",
 "time": { "from": "now-15s", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Speed m/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_ms\")\r\n |> group(columns: [\"_field\"])\r\n |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Speed km/h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_kmph\")\r\n |> group(columns: [\"_field\"])\r\n |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Orientation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"backward\" or r[\"_field\"] == \"forward\" or r[\"_field\"] == \"left\" or r[\"_field\"] == \"right\" or r[\"_field\"] == \"upside_down\")\r\n |> group(columns: [\"_field\"])\r\n |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "BMI_ACCEL_GAUGE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ax\" or r[\"_field\"] == \"ay\" or r[\"_field\"] == \"az\")\r\n |> group(columns: [\"_field\"])\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BMI_GYRO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gx\" or r[\"_field\"] == \"gy\" or r[\"_field\"] == \"gz\")\r\n |> aggregateWindow(every: 1s, fn: mean)\r\n |> group(columns: [\"_field\"])\r\n |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "BMI_ACCEL",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"BUCKET\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ax\" or r[\"_field\"] == \"ay\" or r[\"_field\"] == \"az\")\r\n |> aggregateWindow(every: 1s, fn: mean)\r\n |> group(columns: [\"_field\"])\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n |> yield(name: \"last\")\r\n"
    }
   ]
  }
 ]
}